import type { NextConfig } from "next";

/**
 * STATIC_EXPORT=true builds a fully static site (used for GitHub Pages).
 * In that mode there is no server: proxy.ts and /api/contact are removed by
 * the Pages workflow, the root "/" redirect is generated by
 * scripts/pages-postbuild.mjs and the contact form posts to
 * NEXT_PUBLIC_CONTACT_ENDPOINT (or falls back to email).
 */
const staticExport = process.env.STATIC_EXPORT === "true";
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";

const nextConfig: NextConfig = {
  ...(staticExport && {
    output: "export",
    trailingSlash: true,
    basePath: basePath || undefined,
  }),
  images: {
    // The static export has no image optimisation server.
    unoptimized: staticExport,
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 828, 1080, 1280, 1600, 1920, 2560],
  },
  poweredByHeader: false,
  ...(!staticExport && {
    async headers() {
      return [
        {
          source: "/:path*",
          headers: [
            { key: "X-Content-Type-Options", value: "nosniff" },
            { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
            { key: "X-Frame-Options", value: "SAMEORIGIN" },
          ],
        },
      ];
    },
  }),
};

export default nextConfig;
