/**
 * Writes the Asset Inventory (Asset Strategy — "Existing Research Assets")
 * to docs/ASSET-INVENTORY.md and docs/asset-inventory.csv, combining the
 * research rows in src/content/asset-inventory.ts with every media slot used
 * by the site.
 *
 *   npm run inventory
 */
import { writeFileSync } from "node:fs";
import { inventory, type InventoryItem } from "../src/content/asset-inventory";
import { collectMedia } from "./collect-media";

const STATUS_LABEL: Record<string, string> = {
  verified: "🟢 VERIFIED",
  web: "🔵 WEB",
  generated: "🟣 GENERATED",
  "needs-confirmation": "🟡 NEEDS_CONFIRMATION",
  missing: "🔴 MISSING",
};

const media: InventoryItem[] = collectMedia().map(({ where, category, image, relatedProject }) => {
  const status = image.src ? image.status : image.illustration ? "generated" : "missing";
  return {
    id: `M-${where}`,
    category: category as InventoryItem["category"],
    item: image.brief ?? image.alt.en,
    status,
    url: image.source?.url,
    whatItProves: image.source?.proves,
    usagePermission: image.source?.permission ?? (image.src ? "unknown" : "n/a"),
    confidence: image.source?.confidence,
    relatedProject,
    finalStatus: image.src ? `Photo (${image.status})` : image.illustration ? `GENERATED: ${image.illustration}` : "Placeholder",
  };
});

const rows = [...inventory, ...media];
const cols: (keyof InventoryItem)[] = ["id", "category", "item", "status", "source", "url", "dateFound", "whatItProves", "usagePermission", "confidence", "relatedProject", "finalStatus", "notes"];

const csv = [cols.join(","), ...rows.map((r) => cols.map((c) => `"${String(r[c] ?? "").replace(/"/g, '""')}"`).join(","))].join("\n");
writeFileSync("docs/asset-inventory.csv", csv + "\n");

const counts = Object.entries(STATUS_LABEL).map(([k, label]) => `| ${label} | ${rows.filter((r) => r.status === k).length} |`).join("\n");
const cell = (v: unknown) => String(v ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const table = (list: InventoryItem[]) =>
  `| ID | Category | Item | Status | Source / URL | Proves | Permission | Confidence | Site shows |\n|---|---|---|---|---|---|---|---|---|\n` +
  list
    .map((r) =>
      `| ${cell(r.id)} | ${r.category} | ${cell(r.item)} | ${STATUS_LABEL[r.status]} | ${r.url ? `[${cell(r.source ?? "link")}](${r.url})` : cell(r.source)} | ${cell(r.whatItProves)} | ${cell(r.usagePermission)} | ${cell(r.confidence)} | ${cell(r.finalStatus)} |`,
    )
    .join("\n");

const md = `# Asset Inventory

_Generated by \`npm run inventory\` from \`src/content/asset-inventory.ts\` and the site content. Do not edit by hand._

Priority for every asset: **Original → Web → Generated → Placeholder**. GENERATED visuals are always labelled on the site and never presented as documentation of real work.

| Status | Count |
|---|---|
${counts}

## Research sources & required assets

${table(inventory)}

## Media slots used by the site

${table(media)}
`;
writeFileSync("docs/ASSET-INVENTORY.md", md);
console.log(`inventory: ${rows.length} rows → docs/ASSET-INVENTORY.md, docs/asset-inventory.csv`);
